bases:
  - ../../../base/staging-root

commonLabels:
  domainHash: "262300170"

nameSuffix: "-262300170"

patches:
  - target:
      kind: Deployment
      name: unomi
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/3
        value:
          name: UNOMI_ELASTICSEARCH_INDEXPREFIX
          value: context-262300170